name = "api-worker"
main = "src/index.ts"
compatibility_date = "2024-04-01"

[vars]
JWT_SECRET = "your-next-auth-secret-here"

[[d1_databases]]
binding = "DB"
database_name = "next-hr-db"
database_id = "4fcedbe5-abeb-48d6-899f-617d47217b0a"
