name = "api-worker"
main = "src/index.ts"
compatibility_date = "2024-04-01"

[vars]
JWT_SECRET = "your-next-auth-secret-here"

[[d1_databases]]
binding = "DB"
database_name = "next-hr-db"
database_id = "622b80a5-bc1d-49fc-95fd-a68e09de95f8"
